# Generated by Django 5.0.6 on 2024-06-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('idJuego', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('desarrollador', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='juegos/imagenes')),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('clave', models.FileField(upload_to='juegos/archivos_zip/')),
                ('tipoClave', models.CharField(max_length=40)),
            ],
        ),
    ]
