# Generated by Django 5.0.6 on 2024-06-20 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaSerie',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='nivelEducacional',
            fields=[
                ('idEducacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tipoClave',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='juego',
            name='ytVidId',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='imgJuegos',
            fields=[
                ('idImg', models.IntegerField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='juegos/capturas')),
                ('idJuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.juego')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('idSerie', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='series/imagenes')),
                ('stock', models.IntegerField()),
                ('clave', models.FileField(upload_to='series/claves_zip/')),
                ('ytVidId', models.CharField(max_length=11, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.categoriaserie')),
            ],
        ),
        migrations.CreateModel(
            name='imagenSerie',
            fields=[
                ('idImagen', models.IntegerField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='series/imagenes/')),
                ('idSerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.serie')),
            ],
        ),
        migrations.AlterField(
            model_name='juego',
            name='tipoClave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.tipoclave'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('telefono', models.CharField(max_length=40)),
                ('fechaNac', models.DateField()),
                ('nivelEducacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.niveleducacional')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.region')),
            ],
        ),
    ]
