# Generated by Django 5.0.6 on 2024-06-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_categoriaserie_niveleducacional_region_tipoclave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='juego',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serie',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='serie',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
