# Generated by Django 5.0.6 on 2024-06-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_alter_juego_descripcion_alter_serie_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='idCarro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
