# Generated by Django 5.0.6 on 2024-07-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_juego_desarrollador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='categoria',
        ),
    ]
