# Generated by Django 5.0.6 on 2024-07-12 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_juego_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='desarrollador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.desarrollador'),
        ),
    ]
