# Generated by Django 5.0.6 on 2024-06-22 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_carrito_idcarro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='idUsuario',
            new_name='usuario',
        ),
    ]
