# Generated by Django 5.0.6 on 2024-07-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_juego_desarrollador'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.categoriajuego'),
        ),
    ]
