# Generated by Django 5.0.6 on 2024-06-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_carrito_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='Fechalanz',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='serie',
            name='estudio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='juego',
            name='idJuego',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNac',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
