# Generated by Django 5.0.6 on 2024-06-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_serie_fechalanz_serie_estudio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='Fechalanz',
            new_name='fechalanz',
        ),
    ]
